# From tutorial: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish

on:
  push:
    tags:
      - 'dev/*'

jobs:
  build:
    name: Build and unit test distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish To TestPypi 🐍
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/robotframework-minecraftconsoleclientbindings

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Check if version was bumped
      run: |
        source ./check_new_ver.sh https://test.pypi.org/simple/robotframework-minecraftconsoleclientbindings/
        echo latest_ver is $latest_ver
        echo pyproject_ver is $pyproject_ver

        echo env.latest_ver is ${{ env.latest_ver }}
        echo env.pyproject_ver is ${{ env.pyproject_ver }}
        echo "$GITHUB_ENV"
    - name: Download all the dists
      if: env.latest_ver != env.pyproject_ver
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      if: env.latest_ver != env.pyproject_ver
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  docker-test:
    needs:
    - publish-to-testpypi
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Give pypi 30 seconds to display the new version
        run: sleep 30
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/test-Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zorua162/docker-robotframework-minecraftconsoleclientbindings:test
